"""Shared UI constants for studio modules."""

COMPARE_COL_FONT_SIZE = 14

# KI sidebar / analyse pills
KI_PILL_TEXT_SIZE = 10

# Compare row chrome (evaluate column width)
COMPARE_EVAL_COL_W = 56

# Floating Analyse result card timing
RESULT_CARD_HIDE_DELAY_SEC = 0.18

# Autosave debounce
AUTOSAVE_IDLE_SEC = 6.0

# Side rails
COLLAPSED_RAIL_WIDTH_PX = 36
SIDEBAR_EXPANDED_WIDTH_PX = 280
SIDEBAR_TOOLBAR_ROW_H_PX = 36

KI_TAB_BODY_MIN_HEIGHT_PX = 96
KI_TAB_PAGE_PAD_V_PX = 8
KI_TAB_BAR_TO_PILLS_GAP_PX = 12
KI_TAB_ICON_PX = 18

READING_MAX_PX = 720
COMPOSE_READING_WIDTH_FRAC = 0.92

DIFF_SPAN_CHAR_CAP = 120_000

COMPARE_COL_LINE_HEIGHT = 1.6
COMPOSE_MARGIN_COL_W = 104
COMPARE_PILL_COL_W = 72

RESULT_CARD_W = 380
RESULT_CARD_MAX_H = 360

COMPARE_ACTION_GRID_CELL = 40
COMPARE_ACTION_INNER_W = COMPARE_ACTION_GRID_CELL * 2
COMPARE_ACTION_H_PAD = 5
COMPARE_ACTION_V_PAD = 2
COMPARE_ACTION_COL_W = COMPARE_ACTION_INNER_W + 2 * COMPARE_ACTION_H_PAD

PROJECT_PAGE_URL = "https://www.yourcompanyos.io"
PROJECT_PAGE_TOOLTIP = "Start workflow on {yourcompany}os."

COMPARE_KEY_DRAFT = "__draft__"
COMPARE_KEY_AI = "__ai_preview__"
COMPARE_KEY_PDF_ORIGINAL = "__pdf_original__"
COMPARE_KEY_DOCX_ORIGINAL = "__docx_original__"
